"""Falas curtas do boss/agentes para situações de escritório.

Adaptado pra PT-BR (Jurídico Pro). Não é tradução literal do upstream
`claude-office` — são equivalentes culturais, mantendo o tom (animado /
profissional / casual / motivado / quirky / determinado / tech / curto /
humor de escritório / confiante).
"""

import random

WORK_ACCEPTANCE_QUOTES: list[str] = [
    # Animado
    "Tô nessa!",
    "Bora!",
    "Pego!",
    "Pode considerar feito!",
    "Já é!",
    "Tô em cima!",
    "Pode deixar comigo!",
    "Diz nada!",
    "Beleza, pode crer!",
    "Com certeza!",
    # Profissional
    "Entendido.",
    "Pode deixar.",
    "Anotado.",
    "Confirmado.",
    "Afirmativo.",
    "Recebido.",
    "Câmbio entendido.",
    "Suave.",
    "Sem problema.",
    "Claro.",
    # Casual
    "Tranquilo!",
    "De boa!",
    "Mamão com açúcar!",
    "Moleza!",
    "Deixa comigo!",
    "Olha o show!",
    "Lá vou eu!",
    "Hora do show!",
    "Minha especialidade!",
    "Nasci pra isso!",
    # Motivado
    "Desafio aceito!",
    "Manda ver!",
    "Bora fazer!",
    "Tá ligado!",
    "Pronto pra rodar!",
    "Carregado e pronto!",
    "Missão aceita!",
    "A todo vapor!",
    "Ao seu dispor!",
    "Pra mesa!",
    # Quirky
    "Oba, divertido!",
    "Finalmente!",
    "Adorei a ideia!",
    "Minha hora de brilhar!",
    "Perfeito!",
    "Excelente!",
    "Fantástico!",
    "Show de bola!",
    "Esplêndido!",
    "Maravilhoso!",
    # Determinado
    "Não vou te decepcionar!",
    "Pode confiar.",
    "Pode contar comigo!",
    "Tô na sua!",
    "É minha praia!",
    "Caiu na rede é peixe!",
    "Fui feito pra isso!",
    "É o que eu faço!",
    "Olha e aprende!",
    "Sai da frente!",
    # Tech
    "Compilando ideias...",
    "Processando...",
    "Executando!",
    "Inicializando!",
    "Carregando solução...",
    "Triturando números!",
    "Analisando...",
    "Otimizando!",
    "Fazendo deploy!",
    "Sincronizando!",
    # Curto
    "Aham!",
    "Feito!",
    "Claro!",
    "Sim!",
    "Blz!",
    "Ok!",
    "Aí sim!",
    "Saca!",
    "Fechou!",
    "Show!",
    # Humor de escritório
    "Café primeiro!",
    "Depois do cafezinho!",
    "Hora extra é meu cardio!",
    "Zona livre de reunião!",
    "Inbox zero depois!",
    "Prazo? Que prazo?",
    "Segura meu café!",
    "Pico de produtividade!",
    "Modo foco: ATIVADO",
    "Flow chegando!",
    # Confiante
    "Fácil demais!",
    "Brincadeira de criança!",
    "Simples!",
    "Trivial!",
    "Rapidinho!",
    "Velocidade da luz!",
    "Num piscar de olhos!",
    "Olha isso!",
    "Matei a charada!",
    "Mandei bem!",
]


def get_random_work_acceptance_quote() -> str:
    """Retorna uma fala aleatória de aceitação de trabalho."""
    return random.choice(WORK_ACCEPTANCE_QUOTES)


JOB_COMPLETION_QUOTES: list[str] = [
    # Conclusões clássicas
    "Tudo certo. Projeto entregue!",
    "É o fim da linha! Mandaram bem, time!",
    "Missão cumprida! Trabalho excelente!",
    "Tudo pronto! Hora de comemorar!",
    "Finalizado! Mais um projeto na conta!",
    "Concluído! Trabalho de primeira!",
    "Acabou em grande estilo! Time afiado!",
    "Projeto entregue! Esforço excepcional!",
    "Última peça encaixada! Trabalho brilhante!",
    "Tarefas concluídas! Reverência merecida!",
    # Boss satisfeito
    "Nem eu faria melhor!",
    "É exatamente isso que eu queria!",
    "Superou minhas expectativas! Demais!",
    "Qualidade do começo ao fim!",
    "Tô impressionado! Sério!",
    "Execução de altíssimo nível!",
    "Por isso eu amo esse time!",
    "Entrega impecável! Mandou bem!",
    "Perfeição atingida! Bravo!",
    "Vocês se superaram!",
    # Comemoração
    "Solta o confete! Conseguimos!",
    "Hora da dança da vitória! 🎉",
    "Sucesso! Toca o sino!",
    "Mais uma pra coleção!",
    "Trabalho digno de champanhe! 🍾",
    "Aplausos de pé merecidos!",
    "Hora de comemorar! Trabalho bem feito!",
    "Toca aqui, geral!",
    "Solta o salgadinho! Acabou!",
    "Pizza no escritório! 🍕",
    # Satisfação profissional
    "Todos os requisitos atendidos. Deploy!",
    "Testes passaram. Tá limpo. Perfeito!",
    "Pronto pra produção! Mandou bem!",
    "Cliente vai amar! Show de bola!",
    "No prazo, dentro do orçamento. Lenda!",
    "Zero bugs! Inacreditável!",
    "Daqui pra frente é tranquilo!",
    "Pronto pra subir! Bora pro ar!",
    "Documentação completa! Pode subir!",
    "Code review aprovado! Excelente!",
    # Boss casual
    "Mandou bem! Vocês arrebentam!",
    "Esse aí pegou diferente! Sensacional!",
    "Beijo do chef! Perfeito! 👨‍🍳",
    "Sem ressalvas! Tá uma beleza!",
    "Manda ver! Tá dourado!",
    "Tranca! Execução perfeita!",
    "É assim que se faz! Pou!",
    "Momento mic drop! 🎤",
    "Status lendário desbloqueado!",
    "Construído de outro jeito!",
    # Tech
    "Build verde! Pipeline limpa!",
    "Todos os sistemas operantes! 🚀",
    "Commit no merge! Release pronta!",
    "Exit code 0! Sucesso puro!",
    "100% de cobertura! Lindo!",
    "Lint passou! Código limpo!",
    "Performance otimizada! Voou!",
    "Memory leak? Zero! Perfeito!",
    "Compilação completa! Impecável!",
    "CI/CD: tudo verde! ✅",
    # Motivacional
    "Isso é o que excelência parece!",
    "Time afiado, sonho realizado!",
    "Juntos a gente vai longe! Mandaram bem!",
    "Suor recompensado! Orgulho de vocês!",
    "Sonho virou realidade! Pronto!",
    "Miramos alto e entregamos!",
    "Desafio vencido! Próximo!",
    "Mais uma montanha escalada!",
    "Persistência venceu! Tarefa entregue!",
    "Cada gota de esforço valeu!",
    # Boss aliviado
    "Finalmente! Tá perfeito!",
    "Conseguimos! Que jornada!",
    "Ufa! Foi intenso, mas valeu!",
    "Não acredito que rolou!",
    "Contra todas as probabilidades! Feito!",
    "Prazo batido! Crise evitada!",
    "Scope creep derrotado! Vitória!",
    "Stakeholders vão amar!",
    "Diretoria vai gostar!",
    "Café foi bem investido! Projeto entregue!",
    # Curto e direto
    "Perfeito!",
    "Magnífico!",
    "Soberbo!",
    "Excepcional!",
    "Espetacular!",
    "Fenomenal!",
    "Inacreditável!",
    "Imaculado!",
    "Esplêndido!",
    "Maravilhoso!",
    # Brincalhão
    "Zona livre de bugs! 🐛❌",
    "Código tão limpo que brilha! ✨",
    "Pronto pra deixar usuário feliz!",
    "O eu do futuro agradece!",
    "Isso aí é obra de arte!",
    "Até os testes ficaram impressionados!",
    "Os deuses do código aprovaram!",
    "Pato de borracha aprovou! 🦆",
    "Stack Overflow ia ficar orgulhoso!",
    "10/10, eu subiria de novo!",
]


def get_random_job_completion_quote() -> str:
    """Retorna uma fala aleatória de conclusão de trabalho."""
    return random.choice(JOB_COMPLETION_QUOTES)
